version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - auth_db_data:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=1G

volumes:
  auth_db_data:
