version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - ./data:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=1G
