version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    env_file:
      - database/database.env
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432